/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Desk_1: THREE.Mesh
  }
  materials: {
    ['1001']: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Desk.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[28.67, -28.12, -56.28]}>
        <mesh geometry={nodes.Desk_1.geometry} material={materials['1001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Desk.glb')
